import type { VerificationDashboardData } from "@/lib/verification/types";

export const mockVerificationDashboardData: VerificationDashboardData = {
  subtitle: "Manage your identity and compliance levels",
  tabs: [
    { key: "overview", label: "Verification overview" },
    { key: "tier-1", label: "Tier 1: Basic" },
    { key: "tier-2", label: "Tier 2: Identity" },
    { key: "tier-3", label: "Tier 3: Business" },
  ],
  tiers: [
    {
      id: 1,
      key: "tier-1",
      name: "Tier 1",
      title: "Basic verification",
      dailyLimit: "USD 10,000.00",
      unlocked: true,
      current: true,
      completed: true,
      progress: 100,
      progressLabel: "100% completed",
      helperText: "Your basic profile checks are complete and your wallet is ready for standard payouts.",
      actionLabel: "Verified",
      actionState: "verified",
      requirements: [
        { id: "tier-1-personal-information", label: "Personal information", status: "submitted" },
        { id: "tier-1-email-verification", label: "Email verification", status: "completed" },
        { id: "tier-1-phone-verification", label: "Phone verification", status: "completed" },
      ],
    },
    {
      id: 2,
      key: "tier-2",
      name: "Tier 2",
      title: "Identity verification",
      dailyLimit: "USD 50,000.00",
      unlocked: true,
      current: false,
      completed: false,
      progress: 0,
      progressLabel: "Not started",
      helperText: "Complete the Tier 1 verification requirements to access the Tier 2 verification process.",
      actionLabel: "Complete Tier 2 verification",
      actionState: "available",
      requirements: [
        { id: "tier-2-tier-1", label: "Tier 1 verification process", status: "completed" },
        { id: "tier-2-identification-documents", label: "Identification documents", status: "not-submitted" },
        { id: "tier-2-biometric", label: "Biometric liveness check", status: "incomplete" },
        { id: "tier-2-address", label: "Proof of address", status: "not-submitted" },
      ],
    },
    {
      id: 3,
      key: "tier-3",
      name: "Tier 3",
      title: "Business verification",
      dailyLimit: "Unlimited",
      unlocked: false,
      current: false,
      completed: false,
      progress: 0,
      progressLabel: "Not started",
      helperText: "Complete the Tier 2 verification requirements to access the Tier 3 verification process.",
      actionLabel: "Complete Tier 3 verification",
      actionState: "locked",
      requirements: [
        { id: "tier-3-tier-1", label: "Tier 1 verification process", status: "completed" },
        { id: "tier-3-tier-2", label: "Tier 2 verification process", status: "not-completed" },
        { id: "tier-3-business-credentials", label: "Business credentials", status: "not-submitted" },
        { id: "tier-3-entity-type", label: "Entity type", status: "not-submitted" },
        { id: "tier-3-associates", label: "Associates / stakeholders", status: "not-submitted" },
        { id: "tier-3-ubo", label: "UBO declarations", status: "not-submitted" },
      ],
    },
  ],
  limits: [
    {
      tierId: 1,
      title: "Tier 1: Basic verification limits",
      metrics: [
        { label: "Daily send limit", value: "$500/day" },
        { label: "Max. single transaction", value: "$200" },
        { label: "Monthly cumulative", value: "$2,000" },
        { label: "International wires", value: "Disabled", muted: true },
        { label: "Bulk payments", value: "Disabled", muted: true },
        { label: "Multi-wallet creation", value: "Disabled", muted: true },
      ],
    },
    {
      tierId: 2,
      title: "Tier 2: Identity verification limits",
      metrics: [
        { label: "Daily send limit", value: "$10,000/day" },
        { label: "Max. single transaction", value: "$2,500" },
        { label: "Monthly cumulative", value: "$50,000" },
        { label: "International wires", value: "Enabled" },
        { label: "Bulk payments", value: "Enabled" },
        { label: "Multi-wallet creation", value: "Up to 3 wallets" },
      ],
    },
    {
      tierId: 3,
      title: "Tier 3: Business verification limits",
      metrics: [
        { label: "Daily send limit", value: "Unlimited" },
        { label: "Max. single transaction", value: "Unlimited" },
        { label: "Monthly cumulative", value: "Unlimited" },
        { label: "International wires", value: "Enabled" },
        { label: "Bulk payments", value: "Enabled" },
        { label: "Multi-wallet creation", value: "Unlimited" },
      ],
    },
  ],
};
